# Generated by Django 5.2.6 on 2025-09-14 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeDB', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('alt_names', models.JSONField(blank=True, default=list, null=True)),
                ('ingredients', models.JSONField(blank=True, default=list, null=True)),
                ('method', models.JSONField(blank=True, default=list, null=True)),
                ('tips', models.JSONField(blank=True, default=list, null=True)),
            ],
            options={
                'ordering': ['title'],
                'indexes': [models.Index(fields=['title'], name='RecipeDB_re_title_3c6239_idx'), models.Index(fields=['alt_names'], name='RecipeDB_re_alt_nam_0e2734_idx')],
            },
        ),
    ]
