# Generated by Django 5.2.6 on 2025-09-15 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('alt_names', models.JSONField(blank=True, default=list, null=True)),
                ('ingredients', models.JSONField(blank=True, default=list, null=True)),
                ('method', models.JSONField(blank=True, default=list, null=True)),
                ('tips', models.JSONField(blank=True, default=list, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, choices=[('Veg', 'Veg'), ('Non-Veg', 'Non-Veg'), ('Vegan', 'Vegan'), ('Eggiterian', 'Eggiterian')], max_length=255, null=True)),
            ],
            options={
                'ordering': ['title'],
                'indexes': [models.Index(fields=['title'], name='RecipeAPI_r_title_4713c2_idx'), models.Index(fields=['alt_names'], name='RecipeAPI_r_alt_nam_c34d5c_idx')],
            },
        ),
    ]
